// Conteúdo compartilhado entre Emblemas, Rótulos e Cartões: trilhas e produtos.
// Estilos, ícones, formatos e backgrounds vivem em brandTokens.js.
// Re-exportamos aqui para compatibilidade com imports antigos.
export {
  STYLES,
  SHAPES,
  LANGUAGES,
  LINE_ICONS as ICONS,
  STAGE_BG,
  getStyle,
  getLanguage,
} from "./brandTokens";

export const TRILHAS = [
  {
    id: "diaadia",
    nome: "Bolos & Bases do Dia a Dia",
    sub: "o dia a dia que vende sozinho",
    linha: "Linha Dia a Dia",
    produtos: [
      {
        key: "bolo",
        nome: "Bolo Caseiro",
        tagline: "feito à mão · receita da vovó",
        ring: "ARTESANAL · FEITO EM CASA",
        claim: null,
        desc: "Massa fofinha, cobertura na medida certa. O bolo de todo dia que vira pedido de todo dia.",
        variant: { sabor: "fubá cremoso" },
        peso: "900 g",
        validade: "5 dias refrigerado",
        contem: "trigo, ovos, leite. Pode conter traços de amendoim e castanhas.",
      },
      {
        key: "rocambole",
        nome: "Rocambole Artesanal",
        tagline: "recheio generoso · enrolado à mão",
        ring: "FEITO À MÃO · SEM PRESSA",
        claim: null,
        desc: "Massa fina e recheio na medida, enrolado um a um pra chegar perfeito na sua mesa.",
        variant: { descricao: "massa pronta para rechear e enrolar" },
        peso: "rende 3 rocamboles de 30×40cm",
        validade: "3 dias refrigerado / 60 dias congelado",
        contem: "trigo, ovos, leite. Pode conter traços de soja.",
      },
      {
        key: "hamburguer",
        nome: "Hambúrguer Artesanal",
        tagline: "pão fresco · fermentação lenta",
        ring: "FERMENTAÇÃO LENTA",
        claim: null,
        desc: "Pão macio por dentro, crocante por fora. Feito em pequenos lotes, todo santo dia.",
        variant: { descricao: "massa pré-assada, só finalizar" },
        peso: "rende 8 unidades de 90 g",
        validade: "4 dias em temp. ambiente / 60 dias congelado",
        contem: "trigo, ovos, leite, soja. Pode conter traços de gergelim.",
      },
    ],
  },
  {
    id: "funcional",
    nome: "Confeitaria Funcional",
    sub: "sem lactose, sem glúten e sem açúcar. Alto ticket",
    linha: "Linha Funcional",
    produtos: [
      {
        key: "lactosefree",
        nome: "Confeitaria Sem Lactose",
        tagline: "leites e cremes vegetais",
        ring: "SABOR DE VERDADE",
        claim: "SEM LACTOSE",
        desc: "Todo o sabor da confeitaria clássica, sem nenhum ingrediente de origem láctea na receita.",
        variant: { descricao: "feito com leites e cremes vegetais" },
        peso: "500 g",
        validade: "4 dias refrigerado",
        contem: "trigo, ovos. Não contém leite ou derivados. Pode conter traços de castanhas.",
      },
      {
        key: "glutenfree",
        nome: "Confeitaria Sem Glúten",
        tagline: "farinhas alternativas selecionadas",
        ring: "LEVE E SEGURO",
        claim: "SEM GLÚTEN",
        desc: "Receita testada com farinhas sem glúten, pensada pra quem não pode abrir mão do sabor.",
        variant: { descricao: "feito com farinhas alternativas" },
        peso: "500 g",
        validade: "4 dias refrigerado",
        contem: "ovos, leite. Não contém glúten. Produzido em ambiente que também manipula trigo.",
      },
      {
        key: "sugarfree",
        nome: "Doces Sem Açúcar",
        tagline: "adoçado com: ___________",
        ring: "DOCE NA MEDIDA",
        claim: "SEM AÇÚCAR",
        desc: "Doçura equilibrada com adoçantes naturais, sem abrir mão da textura irresistível.",
        variant: { descricao: "adoçado com: ___________" },
        peso: "400 g",
        validade: "5 dias refrigerado",
        contem: "trigo, ovos, leite. Contém edulcorante. Consumo com moderação.",
      },
    ],
  },
  {
    id: "sazonal",
    nome: "Confeitaria Sazonal",
    sub: "geladinhos, kids e páscoa. Datas que explodem em pedidos",
    linha: "Linha Sazonal",
    produtos: [
      {
        key: "geladinho",
        nome: "Geladinho Gourmet",
        tagline: "sabor: ninho com nutella",
        ring: "GOURMET · FEITO À MÃO",
        claim: null,
        desc: "Cremoso, gelado na medida certa e cheio de sabor. O queridinho do verão.",
        variant: { sabor: "ninho com nutella" },
        peso: "90 ml",
        validade: "60 dias congelado, −18 °C",
        contem: "leite, amendoim, soja. Manter congelado até o consumo.",
      },
      {
        key: "kids",
        nome: "Lanches Kids",
        tagline: "sabor: chocolate com granulado",
        ring: "FEITO PARA A GAROTADA",
        claim: null,
        desc: "Porção certinha, sabor que as crianças amam e os pais aprovam.",
        variant: { sabor: "chocolate com granulado" },
        peso: "80 g",
        validade: "3 dias refrigerado",
        contem: "trigo, ovos, leite, soja. Sem corantes artificiais.",
      },
      {
        key: "ovo",
        nome: "Ovos de Páscoa Artesanal",
        tagline: "recheio: brigadeiro belga",
        ring: "EDIÇÃO DE PÁSCOA",
        claim: null,
        desc: "Casca fina, recheio generoso. Feito em pequenos lotes só para a época da Páscoa.",
        variant: { recheio: "brigadeiro belga" },
        peso: "250 g",
        validade: "60 dias em local fresco e seco",
        contem: "leite, soja, glúten (traços). Conservar longe da luz solar.",
      },
    ],
  },
];

export const DEFAULT_BRAND = "DELÍCIAS LUCRATIVAS";
