export const COURSES_SEED = [
  // COMBO PRINCIPAL: Delícias Lucrativas (Bolos + Iogurtes + Rocamboles + Hamburgão)
  {
    slug: "delicias-lucrativas",
    title: "Delícias Lucrativas",
    tagline: "Domine cinco campeões de vendas e transforme sua cozinha em um negócio altamente rentável.",
    description: "O combo definitivo da culinária lucrativa: Bolos Caseiros, Iogurtes Gourmet, Brigadeiro Gourmet, Base Profissional para Rocamboles e Base Profissional para Hamburguer reunidos em um único curso, organizados em módulos para você diversificar produtos e faturar todos os dias da semana.",
    instructor: "Cozinha Lucrativa",
    duration: "18h 15min",
    level: "Iniciante ao Avançado",
    price: 47.00,
    currency: "brl",
    cover_image: "/images/bolo-caseiro.jpg",
    combined_from: ["bolos-caseiros", "iogurtes-gourmet", "brigadeiro-gourmet", "rocambole-lucrativo", "hamburgao-lucrativo"],
    category: "start",
    tags: ["Combo 5 em 1", "Alta margem", "Múltiplos produtos", "Cliente recorrente"],
    initial_investment: "R$ 250 a 600",
    sales_potential: "R$ 7.500+/mês",
    ideal_for: "Quem quer diversificar produtos e vender todo dia",
    differential_title: "5 Modelos de Negócio em 1",
    differential_text: "Bolos caseiros para encomenda semanal, iogurtes gourmet para venda diária, brigadeiros gourmet para presente, rocamboles para vitrine e hambúrguer artesanal para delivery — venda todos os dias da semana com produtos diferentes.",
    highlights: [
      "Bolos Caseiros — encomenda semanal recorrente",
      "Iogurtes Gourmet — venda diária de alta margem",
      "Brigadeiro Gourmet — alto ticket e cliente fiel",
      "Base Profissional para Rocamboles — venda de vitrine com alta procura",
      "Base Profissional para Hamburguer — delivery de ticket alto",
      "Precificação, marketing e páginas de venda prontas",
    ],
    modules: [],
  },
  // COMBO NICHOS: Confeitaria Funcional Lucrativa (Lactose + Glúten + Diabéticos)
  {
    slug: "confeitaria-fitness",
    title: "Confeitaria Funcional Lucrativa",
    tagline: "Atenda os nichos que mais crescem no mercado com produtos saudáveis e de alto valor agregado.",
    description: "Domine quatro nichos premium da confeitaria: sem lactose, sem glúten, sem açúcar e low carb. Clientes fiéis que pagam bem por qualidade, segurança alimentar e sabor. Tudo em um único curso com receitas testadas e páginas de vendas prontas.",
    instructor: "Cozinha Lucrativa",
    duration: "11h 25min",
    level: "Iniciante",
    price: 47.00,
    currency: "brl",
    cover_image: "/images/alimento-saudavel.png",
    combined_from: ["receitas-lactose", "receitas-zero-gluten", "receitas-diabeticos", "receitas-low-carb"],
    category: "niche",
    tags: ["4 Nichos Premium", "Alta margem", "Cliente fiel", "Produto premium"],
    initial_investment: "R$ 200 a 500",
    sales_potential: "R$ 6.000+/mês",
    ideal_for: "Quem quer atender nichos exclusivos e fiéis",
    differential_title: "4 Nichos Premium em 1 Curso",
    differential_text: "Sem Lactose, Sem Glúten, Sem Açúcar e Low Carb — atenda públicos que pagam mais por qualidade, segurança alimentar e sabor. Clientes recorrentes de alta margem.",
    highlights: [
      "Sem Lactose — mercado em crescimento acelerado",
      "Sem Glúten — celíacos pagam por qualidade certificada",
      "Sem Açúcar — diabéticos e diet, ticket alto",
      "Low Carb — público fitness paga mais e é fiel",
      "Receitas testadas + páginas de venda prontas",
    ],
    modules: [],
    bonuses: [
      {
        id: "confeitaria-fitness-bonus-fit-almoco-janta",
        title: "Receitas Fit para Almoço e Janta",
        type: "pdf",
        url: "/materiais/receitas-fit-almoco-janta.pdf",
        description: "E-book de receitas fit prontas para o almoço e janta — perfeito para vender junto do seu portfólio funcional.",
      },
    ],
  },
  // COMBO SAZONAL: Confeitaria Sazonal Lucrativa (Geladinhos + Lanches Kids + Ovos de Páscoa)
  {
    slug: "confeitaria-alta-demanda",
    title: "Confeitaria Sazonal Lucrativa",
    tagline: "Lucre o ano inteiro com produtos campeões de vendas em cada época e ocasião especial.",
    description: "Domine produtos campeões de vendas para lucrar em diferentes épocas do ano e ampliar suas oportunidades de faturamento. Geladinhos Gourmet, Lanches Kids e Ovos de Páscoa artesanais — três produtos de alta procura reunidos em um único curso.",
    instructor: "Cozinha Lucrativa",
    duration: "14h 20min",
    level: "Iniciante",
    price: 47.00,
    currency: "brl",
    cover_image: "/images/ovo-pascoa.jpg",
    combined_from: ["geladinhos-gourmet", "receitas-kids", "plr-pascoa"],
    category: "seasonal",
    tags: ["Alta procura", "Sazonal + Diário", "3 Modelos em 1", "Alta margem"],
    initial_investment: "R$ 150 a 500",
    sales_potential: "R$ 8.000+/mês (temporada)",
    ideal_for: "Faturar todo mês + explosão em datas comemorativas",
    differential_title: "Delícias para Todas as Ocasiões",
    differential_text: "Geladinhos gourmet, lanches kids e ovos artesanais para aumentar seu faturamento o ano inteiro. Combinação perfeita de venda diária + explosão sazonal em datas comemorativas.",
    highlights: [
      "Geladinhos Gourmet — venda diária de baixo investimento",
      "Lanches Kids — festas, escolas e eventos infantis",
      "Ovos de Páscoa Artesanais — 30 dias de faturamento explosivo",
      "Combinação estratégica: fluxo o ano inteiro",
    ],
    modules: [],
  },
  // CATEGORIA: Comece seu Negócio (start)
  {
    slug: "geladinhos-gourmet",
    title: "Geladinhos Gourmet Lucrativos",
    tagline: "Modelo de negócio de baixíssimo investimento com venda diária.",
    description: "Aprenda receitas exclusivas, precificação, marketing e faturamento com geladinhos gourmet. Método completo em módulos práticos com material de apoio em PDF e páginas de vendas prontas.",
    instructor: "Cozinha Lucrativa",
    duration: "6h 30min",
    level: "Iniciante",
    price: 27.00,
    currency: "brl",
    cover_image: "/images/geladinho.jpg",
    drive_folder_id: "1AU4wWMtHYZnc0Gz0h-z8yaKCVK-8qKyE",
    category: "start",
    tags: ["Baixo investimento", "Venda diária", "Produção doméstica", "Alta procura"],
    initial_investment: "R$ 80 a 200",
    sales_potential: "R$ 2.500+/mês",
    ideal_for: "Quem quer começar com pouca grana",
    modules: [],
  },
  {
    slug: "bolos-caseiros",
    title: "Bolos Caseiros Lucrativos",
    tagline: "Transforme seu forno em uma máquina de encomendas semanais.",
    description: "Curso completo com módulos, planilhas de precificação, receituário em PDF, logo de marca e páginas de vendas. Do sabor tradicional às versões vendedoras.",
    instructor: "Cozinha Lucrativa",
    duration: "5h 20min",
    level: "Iniciante ao Avançado",
    price: 27.00,
    currency: "brl",
    cover_image: "/images/bolo-caseiro.jpg",
    drive_folder_id: "167yf5q5os5E-15zNJbeVZiQAAV-kUIJM",
    category: "start",
    tags: ["Alta margem", "Cliente recorrente", "Encomenda", "Produção doméstica"],
    initial_investment: "R$ 150 a 400",
    sales_potential: "R$ 3.500+/mês",
    ideal_for: "Quem quer viver de encomendas",
    modules: [],
  },
  {
    slug: "receitas-low-carb",
    title: "Receitas Low Carb",
    tagline: "Doces e salgados low carb que vendem alto e fidelizam clientes fitness.",
    description: "Curso completo de receitas low carb para vender em nicho de alta demanda: barrinhas de nuts, brigadeiros e pão de queijo com preparo prático, apostilas em PDF e VSL de vendas. Perfeito para atender o público fitness e saudável que paga mais.",
    instructor: "Cozinha Lucrativa",
    duration: "2h",
    level: "Iniciante",
    price: 27.00,
    currency: "brl",
    cover_image: "/images/receitas-low-carb.webp",
    drive_folder_id: "16rggVkV9fCLzy1aADy8bwm2naYBVBWG_",
    extra_drive_folders: [
      { folder_id: "18coxvzzSX0haeXsbC_nJWXnRwLEnrafN", module_title: "01 Boas Vindas" },
      { folder_id: "18dMbZcVS_cix1bau_AJZw6MpXftr8lEq", module_title: "📚 Materiais" },
    ],
    category: "niche",
    tags: ["Público fitness", "Alto ticket", "Baixo carboidrato", "Cliente fiel"],
    initial_investment: "R$ 150 a 300",
    sales_potential: "R$ 3.500+/mês",
    ideal_for: "Quem quer atender o público fitness e saudável",
    modules: [],
  },
  {
    slug: "brigadeiro-gourmet",
    title: "Brigadeiro Gourmet Lucrativo",
    tagline: "E-book completo + banco de imagens para vender brigadeiros artesanais de alto ticket.",
    description: "Aprenda a produzir e vender brigadeiros gourmet com o e-book completo e um pack de imagens profissionais para redes sociais. Modelo enxuto, prático e de baixíssimo investimento — perfeito para começar a lucrar com brigadeiros artesanais.",
    instructor: "Cozinha Lucrativa",
    duration: "1h 30min",
    level: "Iniciante",
    price: 27.00,
    currency: "brl",
    cover_image: "/images/brigadeiro-gourmet.png",
    extra_drive_folders: [
      { folder_id: "17FNsUg4XHy_EmE897FoMg1-0d2YaAipl", module_title: "📚 Materiais" },
      { folder_id: "1MrYv3EQIQfQPhG20uhZ1pBteUQfUGdjS", module_title: "🎁 Bônus" },
    ],
    masterclass: [
      {
        id: "brigadeiro-masterclass-01",
        title: "Masterclass de Brigadeiros",
        type: "video",
        url: process.env.NEXT_PUBLIC_MASTERCLASS_BRIGADEIROS_URL || "",
        description: "Aula completa com técnicas profissionais de brigadeiro gourmet.",
      },
    ],
    upcoming_modules: [
      { id: "brigadeiro-modulo-01", title: "Módulo 01 — Fundamentos do Brigadeiro Gourmet" },
      { id: "brigadeiro-modulo-02", title: "Módulo 02 — Escolha de Ingredientes e Chocolates" },
      { id: "brigadeiro-modulo-03", title: "Módulo 03 — Ponto Perfeito e Textura" },
      { id: "brigadeiro-modulo-04", title: "Módulo 04 — Sabores Campeões de Vendas" },
      { id: "brigadeiro-modulo-05", title: "Módulo 05 — Recheios e Coberturas Especiais" },
      { id: "brigadeiro-modulo-06", title: "Módulo 06 — Embalagem e Apresentação Premium" },
      { id: "brigadeiro-modulo-07", title: "Módulo 07 — Precificação e Margem de Lucro" },
      { id: "brigadeiro-modulo-08", title: "Módulo 08 — Fotografia e Divulgação em Redes" },
      { id: "brigadeiro-modulo-09", title: "Módulo 09 — Encomendas, Eventos e Pós-Venda" },
      { id: "brigadeiro-modulo-10", title: "Módulo 10 — Escalando o Negócio" },
    ],
    category: "start",
    tags: ["Baixo investimento", "Alta margem", "Encomenda", "Produção doméstica"],
    initial_investment: "R$ 80 a 200",
    sales_potential: "R$ 2.500+/mês",
    ideal_for: "Quem quer começar com pouca grana e alta margem",
    modules: [],
  },
  {
    slug: "iogurtes-gourmet",
    title: "Iogurtes Gourmet Lucrativos",
    tagline: "Iogurtes artesanais de alta margem — venda diária com investimento baixo.",
    description: "Aprenda a produzir iogurtes gourmet artesanais que vendem todo dia. Curso completo com módulos práticos, apostila em PDF, material de apoio e imagens prontas para divulgação. Ideal para quem quer entrar em um mercado em crescimento com investimento reduzido.",
    instructor: "Cozinha Lucrativa",
    duration: "3h 30min",
    level: "Iniciante",
    price: 27.00,
    currency: "brl",
    cover_image: "/images/iogurtes-gourmet.png",
    drive_folder_id: "15H2F1Cu2Mj3WlJKDU9dI2_HLJqfNwhkr",
    extra_drive_folders: [
      { folder_id: "1E07W6jwhNEo61l4cQjw6e0NJMOXmfZml", module_title: "Módulo 01" },
      { folder_id: "1c9qMSP0zGWvjZ8VKy5kdAqPEg4_C08hg", module_title: "🎁 Bônus" },
      { folder_id: "19248vJZ12aX9j27FJ-8fzmrq-hetxPEa", module_title: "📚 Materiais" },
    ],
    category: "start",
    tags: ["Baixo investimento", "Venda diária", "Alta margem", "Cliente recorrente"],
    initial_investment: "R$ 100 a 250",
    sales_potential: "R$ 3.000+/mês",
    ideal_for: "Quem quer entrar num nicho em crescimento",
    modules: [],
  },
  {
    slug: "hamburgao-lucrativo",
    title: "Base Profissional para Hamburguer",
    tagline: "Prepare massas leves e estruturadas para hamburgões irresistíveis e de alta lucratividade.",
    description: "Do preparo da carne ao ponto ideal do pão, sirva hambúrgueres artesanais que fidelizam clientes. Inclui aulas em vídeo, VSL de vendas e página pronta.",
    instructor: "Cozinha Lucrativa",
    duration: "4h 15min",
    level: "Intermediário",
    price: 27.00,
    currency: "brl",
    cover_image: "/images/hamburguer.png",
    drive_folder_id: "1hpYRr9-3QmuZ_n0aWa_4o9KqHqrGuQky",
    category: "start",
    tags: ["Alta margem", "Delivery", "Ticket alto", "Produto premium"],
    initial_investment: "R$ 300 a 600",
    sales_potential: "R$ 5.000+/mês",
    ideal_for: "Quem quer entrar no delivery",
    modules: [],
    apostilas: [
      {
        id: "hamburgao-apostila-oficial",
        title: "Apostila Completa — Hamburgão Lucrativo",
        type: "pdf",
        url: "/apostilas/hamburgao-lucrativo-apostila.pdf",
        description: "Material didático oficial cobrindo as 10 aulas do curso — passo a passo, dicas do chef, precificação e estratégias de venda.",
      },
    ],
  },
  {
    slug: "rocambole-lucrativo",
    title: "Base Profissional para Rocamboles",
    tagline: "Construa a base perfeita para criar rocamboles artesanais de alta qualidade.",
    description: "As receitas dos rocamboles mais vendidos do Brasil, com técnica profissional de enrolamento e recheios cremosos. Ideal para vender por encomenda ou em vitrine.",
    instructor: "Cozinha Lucrativa",
    duration: "3h 40min",
    level: "Iniciante",
    price: 27.00,
    currency: "brl",
    cover_image: "/images/rocambole.png",
    drive_folder_id: "1hABkSgHKFGRAwu68Xbb0NFvIcDfzZOdt",
    category: "start",
    tags: ["Baixo investimento", "Cliente recorrente", "Encomenda", "Produção doméstica"],
    initial_investment: "R$ 100 a 250",
    sales_potential: "R$ 2.500+/mês",
    ideal_for: "Iniciantes que querem alta procura",
    modules: [],
    apostilas: [
      {
        id: "rocamboles-apostila-oficial",
        title: "Apostila Completa — Rocamboles Lucrativos",
        type: "pdf",
        url: "/apostilas/rocamboles-lucrativos-apostila.pdf",
        description: "Material didático oficial cobrindo as 7 aulas do curso — técnica, recheios campeões, dicas do chef e precificação.",
      },
    ],
  },
  // CATEGORIA: Nichos Premium (niche)
  {
    slug: "receitas-lactose",
    title: "Confeitaria Sem Lactose Lucrativa",
    tagline: "Nicho premium: sobremesas sem lactose que fidelizam clientes.",
    description: "Receitas 100% livres de lactose com sabor incrível. Nicho em crescimento e alta margem — atenda pessoas com intolerância que pagam bem por qualidade e segurança alimentar.",
    instructor: "Cozinha Lucrativa",
    duration: "3h 10min",
    level: "Iniciante",
    price: 27.00,
    currency: "brl",
    cover_image: "/images/sem-lactose.png",
    drive_folder_id: "1nypRq1Z8L3fW1-kGgAny5Tc8wEY5j5uR",
    category: "niche",
    tags: ["Produto premium", "Cliente fiel", "Alta margem", "Nicho exclusivo"],
    initial_investment: "R$ 200 a 500",
    sales_potential: "R$ 3.500+/mês",
    ideal_for: "Público com intolerância à lactose",
    modules: [],
  },
  {
    slug: "receitas-zero-gluten",
    title: "Confeitaria Sem Glúten Lucrativa",
    tagline: "Domine o mercado de celíacos e sensíveis ao glúten.",
    description: "Receitas 100% sem glúten para atender celíacos, sensíveis e o público que evita glúten por escolha. Inclui técnicas para pães, bolos e massas que não desandam.",
    instructor: "Cozinha Lucrativa",
    duration: "3h 00min",
    level: "Iniciante",
    price: 27.00,
    currency: "brl",
    cover_image: "/images/sem-gluten.jpg",
    drive_folder_id: "15Pfe4gDmVJm1PYJnG2LX1HXyLnueyUy3",
    category: "niche",
    tags: ["Produto premium", "Cliente fiel", "Alta margem", "Nicho exclusivo"],
    initial_investment: "R$ 200 a 500",
    sales_potential: "R$ 3.500+/mês",
    ideal_for: "Público celíaco e sensível ao glúten",
    modules: [],
  },
  {
    slug: "receitas-kids",
    title: "Lanches Kids Lucrativos",
    tagline: "Doces e lanches infantis com alta procura para festas e escolas.",
    description: "Cardápio para festas infantis, aniversários e lanches escolares. Receitas coloridas, práticas e que as crianças adoram — mães pagam bem por comodidade e qualidade.",
    instructor: "Cozinha Lucrativa",
    duration: "3h 30min",
    level: "Iniciante",
    price: 27.00,
    currency: "brl",
    cover_image: "/images/alimento-saudavel.png",
    drive_folder_id: "1SX9cvUne5A3xA-Hpj5N0HjdidgZiRjQy",
    category: "niche",
    tags: ["Alta procura", "Cliente recorrente", "Festas", "Produção doméstica"],
    initial_investment: "R$ 150 a 300",
    sales_potential: "R$ 3.000+/mês",
    ideal_for: "Mães, festas e escolas",
    modules: [],
  },
  {
    slug: "receitas-diabeticos",
    title: "Doces Sem Açúcar Lucrativos",
    tagline: "Mercado gigante e fiel — doces seguros para diabéticos.",
    description: "Receitas com adoçantes seguros e ingredientes de baixo índice glicêmico. Mercado enorme, disposto a pagar por sabor sem comprometer a saúde.",
    instructor: "Cozinha Lucrativa",
    duration: "3h 15min",
    level: "Iniciante",
    price: 27.00,
    currency: "brl",
    cover_image: "/images/doces-sem-acucar.webp",
    drive_folder_id: "1DUqX_eknrajKIoLzOVXJ4xXqnzjFEFE4",
    category: "niche",
    tags: ["Produto premium", "Cliente fiel", "Alta margem", "Nicho exclusivo"],
    initial_investment: "R$ 200 a 500",
    sales_potential: "R$ 3.000+/mês",
    ideal_for: "Público diabético e diet",
    modules: [],
  },
  // CATEGORIA: Datas Comemorativas (seasonal)
  {
    slug: "plr-pascoa",
    title: "Ovos & Chocolates Artesanais Lucrativos",
    tagline: "Fature em 30 dias o que muita gente fatura o ano todo.",
    description: "Produza ovos de colher, trufados e chocolates artesanais para faturar alto na Páscoa. Material atualizado 2025, criativos, VSL e página de vendas.",
    instructor: "Cozinha Lucrativa",
    duration: "4h 50min",
    level: "Intermediário",
    price: 27.00,
    currency: "brl",
    cover_image: "/images/ovo-pascoa.jpg",
    drive_folder_id: "1V_mbh7a-ogxLsUQTUdKg-IX_gsGvTusw",
    category: "seasonal",
    occasion: "Páscoa",
    tags: ["Alta procura sazonal", "Alta margem", "Produto premium", "Encomenda"],
    initial_investment: "R$ 250 a 500",
    sales_potential: "R$ 8.000+ na temporada",
    ideal_for: "Faturar alto na Páscoa",
    modules: [],
  },
];

export const PLANS = [
  {
    id: "individual",
    name: "1 Curso",
    price: 27.00,
    currency: "brl",
    course_count: 1,
    tagline: "3 modalidades em 1 curso",
    description: "Escolha 1 dos 3 combos completos e comece hoje mesmo.",
    highlight: false,
    features: [
      "1 curso completo (3 modalidades reunidas)",
      "Acesso 12 meses ao conteúdo",
      "Certificado ao concluir",
      "Atualizações incluídas",
    ],
  },
  {
    id: "combo3",
    name: "2 Cursos",
    price: 27.00,
    currency: "brl",
    course_count: 2,
    tagline: "Combine 2 dos 3 combos",
    description: "Escolha 2 cursos completos por um preço único.",
    highlight: true,
    features: [
      "2 cursos completos à sua escolha",
      "Total: 6 modalidades reunidas",
      "Preço único de acesso",
      "Acesso 12 meses + Certificado por curso",
    ],
  },
  {
    id: "library",
    name: "3 Cursos",
    price: 27.00,
    currency: "brl",
    course_count: 3,
    tagline: "Acesso completo",
    description: "Os 3 combos com todas as 9 modalidades reunidas.",
    highlight: false,
    features: [
      "TODOS os 3 cursos disponíveis",
      "Total: 9 modalidades reunidas",
      "Preço único de acesso",
      "Acesso 12 meses + Certificado por curso",
      "Novos combos futuros incluídos",
    ],
  },
];
